library(data.table)
library(dplyr)
library(tidyverse)

setwd("/home/richards/yiheng.chen/scratch/project1_2_metabolomics_GWAS_CLSA/codes/data")
CLSA_NORMDATAALL<-read.csv("./clsa_phenotypes/clsa_batch_norm_metabo_dat",na.strings=c("","NA"," ","Metabolite_not_called_in_this_set", "NaN"))

## metabolomics ADM_GWAS_ID
Metabolon_client_identifier<-read.csv("./clsa_phenotypes/linking_file")
## baseline data
Baseline_data_v5<-read.csv("./clsa_phenotypes/clsa_baseline_data", header=TRUE,stringsAsFactors=FALSE)
##metabolites annotation
matabolites_annotation<-read.csv("./clsa_phenotypes/clsa_metabo_annotation_dat")
#metabolomics metadata
ID_metadat<-read.csv("./clsa_phenotypes/clsa_metabo_meta_dat")
##subset baseline data
Baseline_data_v5_sub<-Baseline_data_v5 %>% select("ADM_GWAS3_COM","entity_id","SEX_ASK_COM", "AGE_NMBR_COM", "HWT_DBMI_COM","BLD_FD24_HR_COM")
colnames(Baseline_data_v5_sub)<-c("ADM_GWAS_COM","entity_id","SEX_ASK_COM", "AGE_NMBR_COM", "HWT_DBMI_COM", "BLD_FD24_HR_COM")

##### read in the ID for unrelated individuals (generated by King)
clsa_unrelated_indiv<-fread("./kingunrelated_list", header =F)

##remove the row without ADM_GWAS_COM
Baseline_data_v5_sub_withADMid<-Baseline_data_v5_sub[is.na(Baseline_data_v5_sub$ADM_GWAS_COM)==FALSE,]
##merge data
dat1<-merge(CLSA_NORMDATAALL, Metabolon_client_identifier, by="PARENT_SAMPLE_NAME")
dat2<-left_join(dat1, Baseline_data_v5_sub_withADMid, by="ADM_GWAS_COM")
dat3<-left_join(dat2, ID_metadat, by="PARENT_SAMPLE_NAME")

##### remove the metabolites have no measurements in >50% of samples
## get the list of metabolites with > 50% missing measurements
dat3_filtered_metaboMeasurement<-dat3 %>% select(X35:X999926111)
metabolite_list<-c()
for(i in names(dat3_filtered_metaboMeasurement)){
  if(sum(is.na(dat3_filtered_metaboMeasurement[[i]]))/length(dat3_filtered_metaboMeasurement[[i]])<0.5){
    metabolite_list<-append(metabolite_list,i)
  }
} ## 1091 metabolites pass this filter
dat4<-dat3 %>% select(PARENT_SAMPLE_NAME,metabolite_list,BLD_FD24_HR_COM,ADM_GWAS_COM)

#### check if there is any individual with over 50% missing
dat4_filtered<-dat4 %>% mutate(missingMeasurement_perce = rowSums(is.na(across(X35:X999926111)))/1091) %>% filter(missingMeasurement_perce<0.5) ## all the individual have >50% measurements

#### get the individual with hour to last meal/drink information
dat5 <-dat4_filtered %>% filter(BLD_FD24_HR_COM>=0) ## 442 individuals have missing information were removed (left 9186)

################################# genomic information
fam_dat<-fread("./clsa_imputed_genotype_data/clsa_gen_v3.fam")
sample_dat<-fread("./clsa_imputed_genotype_data/clsa_imp_v3.sample")
sqc_file<-fread("./clsa_imputed_genotype_data/clsa_sqc_v3.txt")

################ merge metabolomics data and genomic information
### list of individuals without metabolomics measurement or did not pass previous filter
ID_list<-data.frame(cbind(Metabolon_client_identifier$ADM_GWAS_COM, Metabolon_client_identifier$ADM_GWAS_COM))
## get ID for individuals pass previous filter
ID_list_compl<-ID_list[complete.cases(ID_list),]
colnames(ID_list_compl)<-c("FID","IID")
ID_list_no_metabo<-sample_dat %>% select(ID_1, ID_2) %>% filter(!(ID_1 %in% ID_list_compl$FID) | !(ID_1 %in% dat5$ADM_GWAS_COM )) 
colnames(ID_list_no_metabo)<-c("FID","IID")

## prepare a new sample file
sample_dat_sub<-sample_dat %>% filter((ID_1 %in% ID_list_compl$FID) & (ID_1 %in% dat5$ADM_GWAS_COM ))

pop_matching_dat<-data.frame(index=c(1,2,3,4),pop=c("south_asian","east_asian", "black", "europ"))

work_dir="../non_EUR_GWAS"

###### generate PCs for specific Ancestry
for (i in 1:4){
  pop=pop_matching_dat$pop[i]
  sqc_file_sub=sqc_file_all_ancestries%>%filter(pca.cluster.id == i)%>%select(ADM_GWAS_COM)
  sqc_file_sub_ID1<-cbind(sqc_file_sub$ADM_GWAS_COM, sqc_file_sub$ADM_GWAS_COM)
  colnames(sqc_file_sub_ID1)<-c("FID","IID")
  write.table(sqc_file_sub_ID1, paste0(work_dir,pop,"/phenotype/sqc_file_",pop,"_ID.txt"), quote=F, row.names = F, sep="\t")
}
